apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
  namespace: microapp
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
