apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: microapp
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
