apiVersion: v1
kind: Service
metadata:
  name: posts-svc
  namespace: microapp
  labels:
    app: posts
spec:
  selector:
    app: posts
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
