apiVersion: v1
kind: Service
metadata:
  name: users-svc
  namespace: microapp
  labels:
    app: users
spec:
  selector:
    app: users
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
