version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONFIG: production    # pass Angular build configuration
    container_name: angular-prod
    ports:
      - "8080:80"
    restart: unless-stopped
