apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deploy
  namespace: microapp
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: abhi25022004/api-gateway:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: USERS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: microapp-config
                  key: USERS_SERVICE_URL
            - name: POSTS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: microapp-config
                  key: POSTS_SERVICE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: microapp-secrets
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "150m"
              memory: "128Mi"
            limits:
              cpu: "700m"
              memory: "512Mi"
