apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  namespace: microapp
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: abhi25022004/frontend:1.0
          imagePullPolicy: Always 
          ports:
            - containerPort: 80
          env:
            - name: API_BASE_URL
              value: "http://api-gateway-svc.microapp.svc.cluster.local:8080"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
