apiVersion: v1
kind: Pod
metadata:
  name: load-generator
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command: ["/bin/sh"]
    args:
    - -c
    - |
      echo "Starting load test..."
      while true; do
        wget -q -O- http://webapp-service/
        sleep 0.1
      done
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
  restartPolicy: Never