apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-api
  template:
    metadata:
      labels:
        app: social-api
    spec:
      containers:
      - name: social-api
        image: social-api:1.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: social-api
spec:
  type: NodePort
  selector:
    app: social-api
  ports:
  - port: 80
    targetPort: 8080