apiVersion: v1
kind: ConfigMap
metadata:
  name: microapp-config
  namespace: microapp
data:
  API_GATEWAY_PORT: "8080"
  FRONTEND_PORT: "80"
  USERS_SERVICE_URL: "http://users-svc.microapp.svc.cluster.local:8080"
  POSTS_SERVICE_URL: "http://posts-svc.microapp.svc.cluster.local:8080"
